[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Solidity version
solc = "0.8.20"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Sepolia RPC (using a more reliable public node)
[rpc_endpoints]
sepolia = "https://ethereum-sepolia.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
