apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ipfs.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ipfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ipfs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ipfs.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5020
          protocol: TCP
        env:
          {{- toYaml .Values.env | nindent 12 }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: ipfs-data
          mountPath: /app/.ipfs
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: ipfs-data
    spec:
      accessModes: [ "{{ .Values.persistence.accessMode }}" ]
      storageClassName: "{{ .Values.persistence.storageClass }}"
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}

