replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer
  pullPolicy: IfNotPresent
  tag: "v1.16.3"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7300"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  rpc:
    port: 8545
  metrics:
    port: 7300

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  role: core

tolerations:
  - key: workload
    operator: Equal
    value: core
    effect: NoSchedule

affinity: {}

config:
  l1:
    rpcUrl: ""
  rollup:
    rpcUrl: "http://op-node:9545"
  l2oo:
    address: ""
  pollInterval: "12s"
  numConfirmations: 10
  networkTimeout: "10s"
  privateKey: ""  # Should be injected from Vault
  metrics:
    enabled: true
    addr: "0.0.0.0"
    port: 7300
  pprof:
    enabled: false


