apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-geth.fullname" . }}-secrets
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  jwt.hex: {{ .Values.secrets.jwtSecret | quote }}
  {{- else }}
  jwt.hex: "0xa5f4967ffe019fb71673f9a5154412081357e9c4e0191d5560728ed777b8ddb0"
  {{- end }}

