apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-geth.fullname" . }}
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.ws.port }}
    targetPort: ws
    protocol: TCP
    name: ws
  - port: {{ .Values.service.authrpc.port }}
    targetPort: authrpc
    protocol: TCP
    name: authrpc
  - port: {{ .Values.service.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "op-geth.selectorLabels" . | nindent 4 }}

