{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "discord-gateway.fullname" . }}
  labels:
    {{- include "discord-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "discord-gateway.selectorLabels" . | nindent 6 }}
{{- end }}

