{{- if .Values.secrets.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crucible.fullname" . }}-secrets
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.secrets.privateKey | b64enc | quote }}
{{- end }}
