{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager.fullname" . }}-credentials
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.slackWebhookUrl }}
  slack-webhook-url: {{ .Values.secrets.slackWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.pagerdutyServiceKey }}
  pagerduty-service-key: {{ .Values.secrets.pagerdutyServiceKey | b64enc | quote }}
  {{- end }}
{{- end }}
