apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth-l1.fullname" . }}-secrets
  labels:
    {{- include "geth-l1.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  jwt.hex: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  # Generate random JWT secret (32 bytes hex = 64 chars)
  jwt.hex: {{ printf "%x%x%x%x" (randNumeric 8 | atoi) (randNumeric 8 | atoi) (randNumeric 8 | atoi) (randNumeric 8 | atoi) | b64enc | quote }}
  {{- end }}

