apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth-l1.fullname" . }}-secrets
  labels:
    {{- include "geth-l1.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  jwt.hex: {{ .Values.secrets.jwtSecret | quote }}
  {{- else }}
  # JWT secret: 32 bytes in hex = 64 chars (plus 0x prefix for Geth)
  jwt.hex: "0xa5f4967ffe019fb71673f9a5154412081357e9c4e0191d5560728ed777b8ddb0"
  {{- end }}

