apiVersion: v2
name: leaderboard
description: Analytics and Rankings System with Database
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
keywords:
  - analytics
  - leaderboard
maintainers:
  - name: Jeju Network
    email: ops@jeju.network

