# Nitro for Arbitrum Sepolia

resources:
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 2000m
    memory: 8Gi

persistence:
  size: 500Gi

nodeSelector:
  workload: indexer

tolerations:
  - key: workload
    operator: Equal
    value: indexer
    effect: NoSchedule

config:
  chain: "sepolia-rollup"
  parentChain:
    # Use internal Sepolia L1 node
    url: "http://geth-l1.l1.svc.cluster.local:8545"
    beaconUrl: "http://lighthouse.l1.svc.cluster.local:5052"
  execution:
    caching:
      archive: false

