{{- if .Values.serviceAccount.create | default true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leaderboard.serviceAccountName" . }}
  labels:
    {{- include "leaderboard.labels" . | nindent 4 }}
{{- end }}

